parameters:
  pythonVersion: '3.11'
  installExtras: false

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: ${{ parameters.pythonVersion }}
  displayName: "Use Python ${{ parameters.pythonVersion }}"

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    ${{ if eq(parameters.installExtras, 'true') }}:
      pip install pytest pytest-cov flake8
  displayName: "Install Dependencies"